---
- name: Deploy observability role andethereum stack with observability agents
  hosts: all
  become: true


  vars:
    
    jwt_secret_string: "7a813d06b0a08de1f1e70ebbc6b3ec8dc589f62d04d346b4754c9d739b4c648b"
    suggested_fee_recipient: "0xa10214731A6D9eC03d36d1437796D1cEe6a061f7"
    graffiti: SlingNode.com
    enable_firewall: false


  roles:
    - role: geerlingguy.docker
      vars:
        docker_package_state: present
        docker_install_compose_plugin: true
        
    - role: slingnode.ethereum
      when: not monitoring_server | bool

    - role: slingnode.ethereum_observability
