deploy_execution: false
deploy_consensus: false
deploy_validator: true

validator_to_consensus_mapping: "{{ dict(groups.clients_validator | zip(groups.clients_consensus)) }}"

consensus_client_node: "{{ validator_to_consensus_mapping[inventory_hostname] }}"

beacon_node: "http://{{ hostvars[consensus_client_node]['ansible_default_ipv4']['address'] }}:{{ consensus_client_http_port }}"

prysm_beacon_rpc_provider: "{{ hostvars[consensus_client_node]['ansible_default_ipv4']['address'] }}:{{ prysm_rpc_port }}"
prysm_beacon_rpc_gateway_provider: "{{ hostvars[consensus_client_node]['ansible_default_ipv4']['address'] }}:{{ consensus_client_http_port }}"

expose_validator_client_metrics_port_to_host: true